import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import manifest from "./manifest";

// The icon files are generated by scripts/generate-icons.ts and committed. These checks catch a
// file that went missing, a manifest entry that points nowhere, or a size that no longer matches.

const root = path.resolve(__dirname, "../..");
const read = (file: string) => readFileSync(path.join(root, file));

function pngSize(bytes: Buffer) {
  expect(bytes.subarray(1, 4).toString("latin1")).toBe("PNG");
  return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) };
}

describe("favicon.ico", () => {
  const ico = read("src/app/favicon.ico");
  const count = ico.readUInt16LE(4);
  const entries = Array.from({ length: count }, (_, i) => {
    const e = 6 + 16 * i;
    return { size: ico[e] || 256, bpp: ico.readUInt16LE(e + 6), length: ico.readUInt32LE(e + 8), offset: ico.readUInt32LE(e + 12) };
  });

  it("is an icon resource with 16, 32 and 48 px frames at 32 bits", () => {
    expect(ico.readUInt16LE(2)).toBe(1);
    expect(entries.map((e) => e.size)).toEqual([16, 32, 48]);
    for (const e of entries) {
      expect(e.bpp).toBe(32);
      expect(e.offset + e.length).toBeLessThanOrEqual(ico.length);
      expect(ico.readInt32LE(e.offset + 4)).toBe(e.size); // DIB width
      expect(ico.readInt32LE(e.offset + 8)).toBe(e.size * 2); // colour + mask
    }
  });

  it("is round: transparent in the corner, opaque in the middle", () => {
    const { size, offset } = entries[1];
    const alpha = (x: number, y: number) => ico[offset + 40 + ((size - 1 - y) * size + x) * 4 + 3];
    expect(alpha(0, 0)).toBe(0);
    expect(alpha(size / 2, size / 2)).toBe(255);
  });
});

describe("linked icons", () => {
  it("includes a PNG favicon that is a square multiple of 48 px, for Google Search", () => {
    const { width, height } = pngSize(read("src/app/icon1.png"));
    expect(width).toBe(height);
    expect(width % 48).toBe(0);
  });

  it("has a round SVG favicon", () => {
    expect(read("src/app/icon.svg").toString()).toContain('<circle cx="50" cy="50" r="50"');
  });
});

describe("manifest icons", () => {
  const icons = manifest().icons ?? [];

  it("offers 192 and 512 px icons, a maskable one and the SVG", () => {
    expect(icons.map((i) => `${i.sizes} ${i.purpose}`)).toEqual(
      expect.arrayContaining(["192x192 any", "512x512 any", "512x512 maskable", "any any"]),
    );
  });

  it.each(icons.map((i) => [i.src, i]))("%s exists at its declared size", (src, icon) => {
    const file = src === "/icon.svg" ? "src/app/icon.svg" : path.join("public", src);
    const bytes = read(file);
    if (icon.type === "image/png") {
      const { width, height } = pngSize(bytes);
      expect(`${width}x${height}`).toBe(icon.sizes);
    } else {
      expect(icon.type).toBe("image/svg+xml");
      expect(bytes.toString()).toMatch(/^<svg /);
    }
  });
});
