import type { MetadataRoute } from "next";
import { site } from "@/content/site";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: site.name,
    short_name: "Irradiant",
    description: site.description,
    lang: "en-IN",
    start_url: "/",
    display: "minimal-ui",
    background_color: "#f6f7f2",
    theme_color: "#02342b",
    // Generated by scripts/generate-icons.ts. The "any" icons are the round badge; the maskable
    // one is a full-bleed square with the symbol inside the 80% safe zone, for the OS to cut.
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
      { src: "/icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
    ],
  };
}
